// Code generated by protoc-gen-go. DO NOT EDIT.
// source: music.proto

/*
Package musicpb is a generated protocol buffer package.

It is generated from these files:
	music.proto

It has these top-level messages:
	Music
	Author
	MusicRequest
	MusicID
	MusicResponse
*/
package musicpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Music struct {
	SongName     string                     `protobuf:"bytes,1,opt,name=songName" json:"songName,omitempty"`
	AuthorInfo   *Author                    `protobuf:"bytes,2,opt,name=authorInfo" json:"authorInfo,omitempty"`
	Description  string                     `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	SongDuration *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=songDuration" json:"songDuration,omitempty"`
}

func (m *Music) Reset()                    { *m = Music{} }
func (m *Music) String() string            { return proto.CompactTextString(m) }
func (*Music) ProtoMessage()               {}
func (*Music) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Music) GetSongName() string {
	if m != nil {
		return m.SongName
	}
	return ""
}

func (m *Music) GetAuthorInfo() *Author {
	if m != nil {
		return m.AuthorInfo
	}
	return nil
}

func (m *Music) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Music) GetSongDuration() *google_protobuf.Timestamp {
	if m != nil {
		return m.SongDuration
	}
	return nil
}

type Author struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age       string `protobuf:"bytes,2,opt,name=age" json:"age,omitempty"`
	Followers string `protobuf:"bytes,3,opt,name=followers" json:"followers,omitempty"`
	Tracks    string `protobuf:"bytes,4,opt,name=tracks" json:"tracks,omitempty"`
}

func (m *Author) Reset()                    { *m = Author{} }
func (m *Author) String() string            { return proto.CompactTextString(m) }
func (*Author) ProtoMessage()               {}
func (*Author) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Author) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Author) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

func (m *Author) GetFollowers() string {
	if m != nil {
		return m.Followers
	}
	return ""
}

func (m *Author) GetTracks() string {
	if m != nil {
		return m.Tracks
	}
	return ""
}

type MusicRequest struct {
	Add *Music `protobuf:"bytes,1,opt,name=add" json:"add,omitempty"`
}

func (m *MusicRequest) Reset()                    { *m = MusicRequest{} }
func (m *MusicRequest) String() string            { return proto.CompactTextString(m) }
func (*MusicRequest) ProtoMessage()               {}
func (*MusicRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MusicRequest) GetAdd() *Music {
	if m != nil {
		return m.Add
	}
	return nil
}

type MusicID struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *MusicID) Reset()                    { *m = MusicID{} }
func (m *MusicID) String() string            { return proto.CompactTextString(m) }
func (*MusicID) ProtoMessage()               {}
func (*MusicID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MusicID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MusicResponse struct {
	Resp *Music `protobuf:"bytes,1,opt,name=resp" json:"resp,omitempty"`
}

func (m *MusicResponse) Reset()                    { *m = MusicResponse{} }
func (m *MusicResponse) String() string            { return proto.CompactTextString(m) }
func (*MusicResponse) ProtoMessage()               {}
func (*MusicResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MusicResponse) GetResp() *Music {
	if m != nil {
		return m.Resp
	}
	return nil
}

func init() {
	proto.RegisterType((*Music)(nil), "music.Music")
	proto.RegisterType((*Author)(nil), "music.Author")
	proto.RegisterType((*MusicRequest)(nil), "music.MusicRequest")
	proto.RegisterType((*MusicID)(nil), "music.MusicID")
	proto.RegisterType((*MusicResponse)(nil), "music.MusicResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MusicService service

type MusicServiceClient interface {
	AddMusic(ctx context.Context, in *MusicRequest, opts ...grpc.CallOption) (*MusicID, error)
	GetMusic(ctx context.Context, in *MusicID, opts ...grpc.CallOption) (*MusicResponse, error)
}

type musicServiceClient struct {
	cc *grpc.ClientConn
}

func NewMusicServiceClient(cc *grpc.ClientConn) MusicServiceClient {
	return &musicServiceClient{cc}
}

func (c *musicServiceClient) AddMusic(ctx context.Context, in *MusicRequest, opts ...grpc.CallOption) (*MusicID, error) {
	out := new(MusicID)
	err := grpc.Invoke(ctx, "/music.MusicService/AddMusic", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) GetMusic(ctx context.Context, in *MusicID, opts ...grpc.CallOption) (*MusicResponse, error) {
	out := new(MusicResponse)
	err := grpc.Invoke(ctx, "/music.MusicService/GetMusic", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MusicService service

type MusicServiceServer interface {
	AddMusic(context.Context, *MusicRequest) (*MusicID, error)
	GetMusic(context.Context, *MusicID) (*MusicResponse, error)
}

func RegisterMusicServiceServer(s *grpc.Server, srv MusicServiceServer) {
	s.RegisterService(&_MusicService_serviceDesc, srv)
}

func _MusicService_AddMusic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MusicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).AddMusic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/music.MusicService/AddMusic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).AddMusic(ctx, req.(*MusicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_GetMusic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MusicID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).GetMusic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/music.MusicService/GetMusic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).GetMusic(ctx, req.(*MusicID))
	}
	return interceptor(ctx, in, info, handler)
}

var _MusicService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "music.MusicService",
	HandlerType: (*MusicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMusic",
			Handler:    _MusicService_AddMusic_Handler,
		},
		{
			MethodName: "GetMusic",
			Handler:    _MusicService_GetMusic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "music.proto",
}

func init() { proto.RegisterFile("music.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4f, 0xab, 0x40,
	0x14, 0xc5, 0x4b, 0xff, 0x73, 0x69, 0x9b, 0x97, 0xfb, 0x5e, 0x5e, 0x2a, 0x31, 0x4a, 0x58, 0x75,
	0x23, 0x4d, 0x71, 0x6f, 0x52, 0xd3, 0xc4, 0x74, 0xa1, 0x0b, 0x74, 0xe5, 0x8e, 0x32, 0x53, 0x24,
	0x16, 0x06, 0x67, 0x06, 0xfd, 0x62, 0x7e, 0x40, 0xc3, 0x1d, 0x6a, 0x5b, 0xe3, 0x6e, 0xee, 0x3d,
	0x87, 0x73, 0x7e, 0xcc, 0x80, 0x93, 0x57, 0x2a, 0x4b, 0x82, 0x52, 0x0a, 0x2d, 0xb0, 0x47, 0x83,
	0x7b, 0x99, 0x0a, 0x91, 0xee, 0xf8, 0x9c, 0x96, 0x9b, 0x6a, 0x3b, 0xd7, 0x59, 0xce, 0x95, 0x8e,
	0xf3, 0xd2, 0xf8, 0xfc, 0x4f, 0x0b, 0x7a, 0xf7, 0xb5, 0x15, 0x5d, 0x18, 0x2a, 0x51, 0xa4, 0x0f,
	0x71, 0xce, 0xa7, 0x96, 0x67, 0xcd, 0xec, 0xe8, 0x7b, 0xc6, 0x2b, 0x80, 0xb8, 0xd2, 0x2f, 0x42,
	0xae, 0x8b, 0xad, 0x98, 0xb6, 0x3d, 0x6b, 0xe6, 0x84, 0xe3, 0xc0, 0xf4, 0x2d, 0x49, 0x88, 0x8e,
	0x0c, 0xe8, 0x81, 0xc3, 0xb8, 0x4a, 0x64, 0x56, 0xea, 0x4c, 0x14, 0xd3, 0x0e, 0xa5, 0x1d, 0xaf,
	0xf0, 0x06, 0x46, 0x75, 0xf8, 0xaa, 0x92, 0x31, 0x59, 0xba, 0x14, 0xe9, 0x06, 0x06, 0x37, 0xd8,
	0xe3, 0x06, 0x4f, 0x7b, 0xdc, 0xe8, 0xc4, 0xef, 0x33, 0xe8, 0x9b, 0x5e, 0x44, 0xe8, 0x16, 0x07,
	0x64, 0x3a, 0xe3, 0x1f, 0xe8, 0xc4, 0x29, 0x27, 0x4e, 0x3b, 0xaa, 0x8f, 0x78, 0x0e, 0xf6, 0x56,
	0xec, 0x76, 0xe2, 0x83, 0x4b, 0xd5, 0xf0, 0x1c, 0x16, 0xf8, 0x1f, 0xfa, 0x5a, 0xc6, 0xc9, 0xab,
	0x22, 0x0e, 0x3b, 0x6a, 0x26, 0x3f, 0x80, 0x11, 0xdd, 0x4d, 0xc4, 0xdf, 0x2a, 0xae, 0x34, 0x5e,
	0x40, 0x27, 0x66, 0x8c, 0xaa, 0x9c, 0x70, 0xd4, 0xfc, 0xbf, 0x71, 0xd4, 0x82, 0x7f, 0x06, 0x03,
	0x9a, 0xd6, 0x2b, 0x9c, 0x40, 0x3b, 0x63, 0x0d, 0x54, 0x3b, 0x63, 0xfe, 0x02, 0xc6, 0x4d, 0x94,
	0x2a, 0x45, 0xa1, 0x38, 0x7a, 0xd0, 0x95, 0x5c, 0x95, 0xbf, 0x86, 0x91, 0x12, 0x56, 0x4d, 0xfb,
	0x23, 0x97, 0xef, 0x59, 0xc2, 0x71, 0x01, 0xc3, 0x25, 0x63, 0xe6, 0xb1, 0xfe, 0x9e, 0xf8, 0x0d,
	0x9e, 0x3b, 0x39, 0x5e, 0xae, 0x57, 0x7e, 0x0b, 0x43, 0x18, 0xde, 0x71, 0x6d, 0x3e, 0xf9, 0xa1,
	0xba, 0xff, 0x4e, 0x23, 0x0c, 0x96, 0xdf, 0xba, 0xb5, 0x9f, 0x07, 0x24, 0x94, 0x9b, 0x4d, 0x9f,
	0xde, 0xe1, 0xfa, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x29, 0x26, 0x59, 0x5a, 0x02, 0x00, 0x00,
}
